# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: laserscan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='laserscan.proto',
  package='lasermsg',
  syntax='proto3',
  serialized_pb=_b('\n\x0flaserscan.proto\x12\x08lasermsg\"\xc0\x01\n\tLaserscan\x12\x11\n\tangle_min\x18\x01 \x01(\x02\x12\x11\n\tangle_max\x18\x02 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x03 \x01(\x02\x12\x16\n\x0etime_increment\x18\x04 \x01(\x02\x12\x11\n\tscan_time\x18\x05 \x01(\x02\x12\x11\n\trange_min\x18\x06 \x01(\x02\x12\x11\n\trange_max\x18\x07 \x01(\x02\x12\x0e\n\x06ranges\x18\x08 \x03(\x02\x12\x13\n\x0bintensities\x18\t \x03(\x02\x42\x0b\xaa\x02\x08lasermsgb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LASERSCAN = _descriptor.Descriptor(
  name='Laserscan',
  full_name='lasermsg.Laserscan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle_min', full_name='lasermsg.Laserscan.angle_min', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angle_max', full_name='lasermsg.Laserscan.angle_max', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angle_increment', full_name='lasermsg.Laserscan.angle_increment', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_increment', full_name='lasermsg.Laserscan.time_increment', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scan_time', full_name='lasermsg.Laserscan.scan_time', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range_min', full_name='lasermsg.Laserscan.range_min', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range_max', full_name='lasermsg.Laserscan.range_max', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ranges', full_name='lasermsg.Laserscan.ranges', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intensities', full_name='lasermsg.Laserscan.intensities', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=222,
)

DESCRIPTOR.message_types_by_name['Laserscan'] = _LASERSCAN

Laserscan = _reflection.GeneratedProtocolMessageType('Laserscan', (_message.Message,), dict(
  DESCRIPTOR = _LASERSCAN,
  __module__ = 'laserscan_pb2'
  # @@protoc_insertion_point(class_scope:lasermsg.Laserscan)
  ))
_sym_db.RegisterMessage(Laserscan)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\010lasermsg'))
# @@protoc_insertion_point(module_scope)
